### ISSUE TITLE
some build errors

### ISSUE THREAD

**Issue by binutzu** [netsurf-plan9/nsport#1]
Hello,

i would like 1st to say thanks to all involved for the effort of putting this together with netsurf. At last! 

Today i tried out building the port. After figuring out the git branch command option issue (fix came few hours later yay!) i ran into compilation issues.
I am not sure if these are only specific to my build/env.
I wanted to have something running so i tried some dirty hacks.

#1: fs_backing_store.c:1619, near offst
uintmax_t seems to be undefined, so i figured i can easily replace the few occurences with unsigned int

#2: duktape.c:1155, duk_int64_t seems to be undefined
I figured out that on my 386 system 64 bit integers logic of duk_config.h does not detect 64bit types: DUK_F_HAVE_64BIT is undefined. I added some long long types.

Compiled all but then there were linking errors:
talloc_vasprintf: undefined va_copy
nslog__log: undefined va_copy

Did a hack: 
#define va_copy(a,b) (a=b)
and had a bińary which started and could interact with it!
 
Can it be build currently without these changes or am i missing something?
Is the build working only on 64 bit system?

Cheers

**Comment by oridb** [comment]
You'll want to update your system -- there have been a large number of posix compliance issues fixed in 9front as part of doing this port.

For instructions on keeping up to date, take a look at http://fqa.9front.org/fqa5.html

If you're still running into issues, please give the full error -- you can upload to okturing.com via the `webpaste` command.

**Comment by binutzu** [comment]
Thanks for the instructions. i was able to build nsport after updating 9front.

**Comment by potsbaker** [comment]
Hey,
I had a compilation error when building netsurf, here's the log.
I already did a system update/upgrade.
http://okturing.com/src/10672/body
